clang-tidy: Fix Unused Variable Warnings
The following errors were reported during clang-tidy enablement due
to multiple unused variables.

'''
ipmi/dbus_mode.cpp:37:23: error: unused variable 'failsafeProperty' [-Werror
ipmi/dbus_mode.cpp:36:23: error: unused variable 'manualProperty' [-Werror
'''

This fix removes the unused variables to resolve the warnings.

Tested: Build and unit testing verified.

Change-Id: I3abf76b57b939df5cbeb4c71b7063705fe0ff3a8
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>