clang-tidy: Add Tag Names to Anonymous Structs
The following errors were reported during clang-tidy enablement due to
anonymous non-C-compatible types being given names for linkage purposes
by typedef declarations. This fix addresses the issue by adding tag
names to the anonymous structs, making them compatible with C.

'''
pid/ec/pid.hpp:20:15: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror
pid/ec/pid.hpp:11:15: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror
'''

Tested: Build and unit testing verified.

Change-Id: I1a998d23b515f2ff570867935cc1a6c8b040f4b1
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>